added option to streamspray that allows for different potential to be…
jobovy/streamtools pull request #1
Opened 2020-06-24 00:45 UTC by webbjj

added option to streamspray that allows for different potential to be used for tidal radius calculation

2020-06-24 00:59 UTC, jobovy requested changes
Looks good! Some very minor comments

2020-06-24 00:59 UTC, jobovy commented on streamtools/df/streamspraydf.py
> +           rtpot = (None) potential for calculating tidal radius and vircular velocity
vircular -> circular

I would also write
"rtpot = (pot) potential for calculating tidal radius and vircular velocity"
to make it clear that the default is pot

2020-06-24 00:59 UTC, jobovy commented on streamtools/df/streamspraydf.py
> +
Could also do
```
self._rtpot= self._pot if rtpot is None else flatten_potential(rtpot)
```

2020-06-25 00:43 UTC, merged

2020-06-25 00:45 UTC, webbjj commented
Changes made. I think I may have accidentally accepted the pull request though. I meant to just update the file. My bad.

2020-06-25 00:54 UTC, jobovy commented
🎉🎉🎉